# Generated by Django 5.2.8 on 2025-11-27 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='product_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='product_material',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='product_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='product_stock',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='product_alt_text',
            new_name='alt_text',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='product_image',
            new_name='image',
        ),
    ]
