# Generated by Django 5.2.8 on 2025-12-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productdetail_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='stock',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=1),
        ),
    ]
