# Generated by Django 5.2.8 on 2025-11-27 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_order_amount',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_status',
            new_name='status',
        ),
    ]
